apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game
  name: mario-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-game
        image: zm56/super-mario
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  namespace: game
  name: mario-svc
spec:
  type: NodePort
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
